name: Push Images

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "miner-cache/**"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get short sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push targon hub miner cache
        uses: docker/build-push-action@v6
        with:
          context: miner-cache
          push: true
          tags: |
            manifoldlabs/targon-hub-miner-cache:latest
            manifoldlabs/targon-hub-miner-cache:${{ steps.vars.outputs.sha_short }}

      - name: Build and push targon hub vram estimator
        uses: docker/build-push-action@v6
        with:
          context: vram-estimator
          push: true
          tags: |
            manifoldlabs/targon-hub-vram-estimator:latest
            manifoldlabs/targon-hub-vram-estimator:${{ steps.vars.outputs.sha_short }}
